### ISSUE TITLE
Alex Ndeezi appearing twice on PWD list

### ISSUE THREAD

**Issue by tmtmtmtm** [theyworkforyou/uganda-parliament-watch#21]
http://theyworkforyou.github.io/uganda-parliament-watch/post/pwd/10/

![screen shot 2016-05-06 at 07 39 27](https://cloud.githubusercontent.com/assets/57483/15066039/b13e4c98-135d-11e6-8775-1b41c499da55.png)

**Comment by chrismytton** [comment]
Looks like he was in the spreadsheet twice, which was creating two identical memberships for him. I've removed the duplicate row from the spreadsheet and triggered a rebuild.

**Comment by chrismytton** [comment]
Fixed in https://github.com/everypolitician/everypolitician-data/pull/9477

**Comment by chrismytton** [comment]
This is now showing on the live site http://theyworkforyou.github.io/uganda-parliament-watch/post/pwd/10/
