### ISSUE TITLE
Workers' Represantive vs Workers' Representative

### ISSUE THREAD

**Issue by tmtmtmtm** [theyworkforyou/uganda-parliament-watch#22]
![screen shot 2016-05-06 at 07 40 15](https://cloud.githubusercontent.com/assets/57483/15066060/d46784be-135d-11e6-9d30-0d957c2683ac.png)

**Comment by chrismytton** [comment]
Fixed in https://github.com/tmtmtmtm/uganda-parliament-scraper/pull/2. Have triggered a rerun of [the scraper](https://morph.io/everypolitician-scrapers/uganda-parliament-scraper).

**Comment by chrismytton** [comment]
Reopening until the scraper _actually_ finishes running and the data has trickled through to the live site.

**Comment by chrismytton** [comment]
Fixed in https://github.com/everypolitician/everypolitician-data/pull/9480
