### ISSUE TITLE
Nothern vs Northern

### ISSUE THREAD

**Issue by tmtmtmtm** [theyworkforyou/uganda-parliament-watch#28]
We have lots of almost-duplicated districts:
- http://theyworkforyou.github.io/uganda-parliament-watch/district/ocd-division-country-ug-region-nothern-subregion-lango-district-alebtong/
- http://theyworkforyou.github.io/uganda-parliament-watch/district/ocd-division-country-ug-region-northern-subregion-lango-district-alebtong/

**Comment by chrismytton** [comment]
There were 16 instances of this in the spreadsheet. I've corrected all of those now and triggered a rebuild.

**Comment by chrismytton** [comment]
Ah, need to rebuild the [uganda_ocd_ids](https://github.com/theyworkforyou/uganda_ocd_ids) and the rerun the scraper to properly pick up these changes.

**Comment by chrismytton** [comment]
Identifiers rebuilt in https://github.com/theyworkforyou/uganda_ocd_ids/commit/1e06b0a272b6e2461bec159a0d2be36ad69f63e3

**Comment by chrismytton** [comment]
Fixed in https://github.com/everypolitician/everypolitician-data/pull/9480
